booktest/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [

    url(r'^$',views.index,name='index'),
    url(r'^(\d+)$',views.show,name='show'),
    url(r'^index2/$',views.index2,name='index2'),
    url(r'^user1/$',views.user1,name='user1'),
    url(r'^htmlTest/$',views.htmlTest,name='htmlTests'),
    url(r'^csrf1/$', views.csrf1),
    url(r'^csrf2/$', views.csrf2),
]

test2/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('booktest.urls', namespace='booktest'))

]

booktest/models.py
from django.db import models

# Create your models here.

class BookInfoManager(models.Manager):

    def get_queryset(self):

        return super(BookInfoManager,self).get_queryset().filter(isDelete=False)

    def create(self,btitle,bpub_date):
        b = BookInfo()
        b.btitle=btitle
        b.bpub_date=bpub_date
        b.bread=0
        b.bcommet=0
        b.isDelete=False
        return b
class BookInfo(models.Model):

    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField(db_column='pub_date')
    bread = models.IntegerField(default=0)
    bcommet = models.IntegerField(default=0)
    isDelete = models.BooleanField(default=False)

    class Meta:
        db_table='bookinfo'
        #ordering = ['id']

    books1 = models.Manager()
    books2 = BookInfoManager()

    #快捷创建模型类对象
    @classmethod
    def create(cls,btitle,bpub_date):
        b = BookInfo()
        b.btitle=btitle
        b.bpub_date=bpub_date
        b.bread=0
        b.bcommet=0
        b.isDelete=False
        return b




class HeroInfo(models.Model):

    hname = models.CharField(max_length=20)
    hgender = models.BooleanField(default=True)
    isDelete = models.BooleanField(default=False)
    hcontent = models.CharField(max_length=100)
    hbook = models.ForeignKey('BookInfo')

    def showname(self):
        return self.hname

booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from django.db.models import Max,F

from .models import *



# def index(request):
#
#
#     #list = BookInfo.books1.filter(heroinfo__hcontent__contains='八')
#     Max1 = BookInfo.books1.aggregate(Max('bpub_date'))
#
#     list = BookInfo.books1.filter(bread__gt=F('bcommet'))
#     content = {'list':list,
#                'Max1':Max1}
#
#     return render(request,'booktest/index.html',content)


def index(request):
    hero = HeroInfo.objects.get(pk=1)
    list = HeroInfo.objects.filter(isDelete=False)
    context={'list':list}
    return render(request,'booktest/index.html',context)


def show(request,id):
    context = {'id':id}

    return render(request,'booktest/show.html',context)


def index2(request):
    return render(request,'booktest/index2.html')

def user1(request):
    return render(request,'booktest/user1.html')

#html转义
def htmlTest(request):

    context = {'t1':'<h1>123</h1>'}
    return render(request,'booktest/htmlTest.html',context)

#跨站请求
def csrf1(request):
    return render(request,'booktest/csrf1.html')
def csrf2(request):
    uname=request.POST['uname']
    return HttpResponse(uname)

templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logo</title>
    {% block head %}{% endblock %}
</head>
<body>
<hr>
{% block content1 %}
{% endblock %}
<hr>

</body>
</html>

templates/booktest/base_goods.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content1 %}

    <table border="1">

    <tr>
        <td height="300">用户导航</td>
        <td>{% block user_content %} {% endblock %}</td>
    </tr>

    </table>
{% endblock content1 %}
</body>
</html>

templates/booktest/base_user.html
{% extends 'booktest/base.html' %}


{% block content1 %}

    <table border="1">

    <tr>
        <td height="300">用户导航</td>
        <td>{% block user_content %} {% endblock %}</td>
    </tr>

    </table>
{% endblock content1 %}

templates/booktest/csrf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/csrf2/" method="post">
    {% csrf_token %}
    <input type="text" name="uname">
    <input type="submit" value="提交">
</form>

</body>
</html>

templates/booktest/csrf2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ uname }}
</body>
</html>

templates/booktest/htmlTest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ t1 }}
<br />
{{ t1|safe }}
<br />
{% autoescape on %}
    {{ t1 }}
{% endautoescape %}
</body>
</html>

templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'booktest:show' '123'%}">展示</a>
<hr>
<ul>
    {% for hero in list %}
    <li>{{ forloop.counter }}{{ hero.showname }}</li>
    {% empty %}
        <li>啥也没找到</li>
{% endfor %}
</ul>
{#{{ hero.showname }}#}

<br />
<b>{{ Max1 }}</b>


</body>
</html>

templates/booktest/index2.html
{% extends 'booktest/base.html' %}


{% block content1 %}
    <h1>123</h1>
{% endblock content1 %}

templates/booktest/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{ id }}

</body>
</html>

templates/booktest/user1.html
{% extends 'booktest/base_user.html' %}

{% block user_content %}
<h1>用户中心</h1>

{% endblock user_content %}